pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/seyi007i/order-service.git'
            }
        }

	 stage('Change Directory and Build') {
            steps {
                // Change directory and perform tasks
                dir('./order-service') {
                    sh 'echo "Current directory is $(pwd)"'
                    }
                }
            }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Docker Build & Push') {
            steps {
                script {
                    dockerImage = docker.build("yourdockerhub/user-service:${env.BUILD_ID}")
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        dockerImage.push("${env.BUILD_ID}")
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f kubernetes/deployment.yaml'
            }
        }
    }
}
